### PR TITLE
fix: Deleting protocol mappers during config import

### LINKED ISSUE #746: ProtocolMappers not removed properly
### Current Behavior

When I have a client incl. protocol mappers and remove the protocol mappers from code, the mappers are still in place. When I delete the mappers manually and then let the CLI run a second time, they where not re-created.

### Expected Behavior

I would have expected that the protocol mappers are removed when they are removed from code.

### Steps To Reproduce

```markdown
1. Add a client incl. protocol mapper and run the CLI
2. Remove the mapper from code and run the CLI
3. Check if mapper is still in place (actual: still in place, expected: removed)
```

### Environment

- Keycloak Version: 18.0.0
- keycloak-config-cli Version: v5.2.0
- Java Version: 17

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Motouom**
**What this PR does / why we need it**: To be able to delete protocol mappers

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #746

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [X] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: src/main/java/de/adorsys/keycloak/config/util/ProtocolMapperUtil.java [hunk 1]
```diff
@@ -35,23 +33,19 @@ public static List<ProtocolMapperRepresentation> estimateProtocolMappersToRemove
             List<ProtocolMapperRepresentation> protocolMappers,
             List<ProtocolMapperRepresentation> existingProtocolMappers
     ) {
-        List<ProtocolMapperRepresentation> protocolMappersToRemove = new ArrayList<>();
-
-        if (existingProtocolMappers == null) {
-            return protocolMappersToRemove;
+        if (existingProtocolMappers == null || existingProtocolMappers.isEmpty()) {
+            return List.of(); // Return an immutable empty list
```
Comment (AssahBismarkabah) [inline src/main/java/de/adorsys/keycloak/config/util/ProtocolMapperUtil.java:37]: Hi @Motouom 

The setting of `existingProtocolMappers.isEmpty()` must be done before reimporting. This requirement introduces a limitation. It could lead to potential errors if overlooked.  Consider the impact on workflow and efficiency.  A clear process is essential to avoid setbacks.  

image

Comment (Motouom) [reply src/main/java/de/adorsys/keycloak/config/util/ProtocolMapperUtil.java:37]: Hello @AssahBismarkabah,

It's essential to understand the correct method for managing protocol mappers to ensure they are effectively deleted. If you remove the entire `protocolMappers` section from your configuration, any already imported mappers will remain intact.

To properly delete protocol mappers, follow these steps:

1. **To remove a specific mapper**, you must delete that specific entry from the `protocolMappers` array.
2. **To delete all protocol mappers**, you must leave the `protocolMappers` array in the configuration but ensure it is empty.

Here's how the process works:

Your initial configuration will look like this:

```json
{
    "realm": "test-realm",
    "enabled": true,
    "clients": [
        {
            "clientId": "test-client",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "redirectUris": ["*"],
            "webOrigins": ["*"],
            "protocolMappers": [
                {
                    "name": "TestMapper",
                    "protocol": "openid-connect",
                    "protocolMapper": "oidc-usermodel-attribute-mapper",
                    "consentRequired": false,
                    "config": {
                        "userinfo.token.claim": "true",
                        "user.attribute": "testAttribute",
                        "id.token.claim": "true",
                        "access.token.claim": "true",
                        "claim.name": "testClaim",
                        "jsonType.label": "String"
                    }
                }
            ]
        }
    ]
}
```

If you attempt to remove the `protocolMappers` section entirely, the configuration will look like this:

```json
{
    "realm": "test-realm",
    "enabled": true,
    "clients": [
        {
            "clientId": "test-client",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "redirectUris": ["*"],
            "webOrigins": ["*"]
        }
    ]
}
```

This action will not delete the protocol mapper, so do not take this approach.

To effectively ensure the removal of protocol mappers, adjust your configuration to this format:

```json
{
    "realm": "test-realm",
    "enabled": true,
    "clients": [
        {
            "clientId": "test-client",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "redirectUris": ["*"],
            "webOrigins": ["*"],
            "protocolMappers": [
                // This array must be left empty to indicate removal
            ]
        }
    ]
}
```

By maintaining the `protocolMappers` array while leaving it empty, you clearly communicate that there are no remaining protocol mappers.

**Review by AssahBismarkabah — APPROVED** [review]

**Review by Calebasah — APPROVED** [review]
