### PR TITLE
Fix #907 (JSON logging broken)

### LINKED ISSUE #907: Spring profile `json-log` has stopped working
### Current Behavior

When running keycloak-config-cli with spring.profiles.active=json-log it immediately exits with exit code 1.

### Expected Behavior

This used to enable console logging in json format.

I've upgraded from v5.2.0 to v5.8.0, so this must have broke somewhere in between these versions 

### Steps To Reproduce

Add the following properties to `src/main/resources/application.properties`

```
spring.profiles.active=json-log
import.files.locations=src/test/resources/import-files
```

run `mvn spring-boot:run`

### Environment

- Keycloak Version: 22.0.1
- keycloak-config-cli Version: 5.8.0
- Java Version: 17

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kschubert**
fixes #907: add missing dependency jakarta.xml.bind-api; lower logstash version from 7.4 to 7.2 - 7.2 is the last version supporting logback 1.2, which is required by Spring and other components

### CODE REVIEW

File: src/test/java/de/adorsys/keycloak/config/jsonlog/JsonLogTest.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+import static org.hamcrest.Matchers.is;
+
+// From: https://tuhrig.de/testing-configurationproperties-in-spring-boot/
+@ExtendWith(SpringExtension.class)
+@ExtendWith(GithubActionsExtension.class)
+@SpringBootTest(classes = {JsonLogTest.TestConfiguration.class})
+@TestPropertySource(properties = {
+        "spring.main.log-startup-info=true",
+        "spring.profiles.active=json-log",
+
```
Comment (thomasdarimont) [inline src/test/java/de/adorsys/keycloak/config/jsonlog/JsonLogTest.java:44]: Remove empty line

**Comment by thomasdarimont** [comment]
@kschubert thanks for your contribution, would you mind to squash your commits into one for this PR?

File: src/test/java/de/adorsys/keycloak/config/jsonlog/JsonLogTest.java (hunk 1 above)
Comment (kschubert) [reply src/test/java/de/adorsys/keycloak/config/jsonlog/JsonLogTest.java]: Done.
